// Tests the Markdown-to-Gemini-TOML command adapter.
import { describe, expect, it } from 'vitest';

import {
  commandSlugFromPath,
  geminiCommandFileName,
  parseCommandDocument,
  renderGeminiCommand,
  toTomlString,
} from '../../src/harness/CommandAdapter.js';

describe('command adapter', () => {
  it('splits frontmatter description from the prompt body', () => {
    const document = parseCommandDocument('---\ndescription: Ship it\n---\n\n# Deploy\n\nRun the deploy.\n', 'c.md');

    expect(document).toEqual({ description: 'Ship it', prompt: '# Deploy\n\nRun the deploy.' });
  });

  it('treats a file without frontmatter as pure prompt text', () => {
    expect(parseCommandDocument('Just do the thing.\n', 'c.md')).toEqual({ prompt: 'Just do the thing.' });
  });

  it('treats an unterminated frontmatter block as pure prompt text', () => {
    expect(parseCommandDocument('---\ndescription: x\nstill going', 'c.md')).toEqual({
      prompt: '---\ndescription: x\nstill going',
    });
  });

  it('ignores frontmatter that is not a mapping or not valid YAML', () => {
    expect(parseCommandDocument('---\n- a\n- b\n---\nbody', 'c.md')).toEqual({ prompt: 'body' });
    expect(parseCommandDocument('---\n: :\n---\nbody', 'c.md')).toEqual({ prompt: 'body' });
    expect(parseCommandDocument('---\nnull\n---\nbody', 'c.md')).toEqual({ prompt: 'body' });
  });

  it('ignores a non-string description', () => {
    expect(parseCommandDocument('---\ndescription: 12\n---\nbody', 'c.md')).toEqual({ prompt: 'body' });
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-011.4.2).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('renders TOML that identifies itself as generated', () => {
    const rendered = renderGeminiCommand({ description: 'Ship it', prompt: 'line one\nline two' });

    expect(rendered.startsWith('# Generated by `outfitter link`.')).toBe(true);
    expect(rendered).toContain('description = "Ship it"');
    expect(rendered).toContain('prompt = "line one\\nline two"');
  });

  it('omits the description key when the source has none', () => {
    expect(renderGeminiCommand({ prompt: 'body' })).not.toContain('description =');
  });

  it('escapes characters that are not legal raw in a TOML basic string', () => {
    expect(toTomlString('a"b')).toBe('"a\\"b"');
    expect(toTomlString('a\\b')).toBe('"a\\\\b"');
    expect(toTomlString('a\tb\r\nc')).toBe('"a\\tb\\r\\nc"');
    // A C0 control with no shorthand escape becomes a \u sequence.
    expect(toTomlString(`a${String.fromCodePoint(0x07)}b`)).toBe('"a\\u0007b"');
    expect(toTomlString(String.fromCodePoint(0x7f))).toBe('"\\u007f"');
  });

  it('maps a namespaced command slug onto Gemini dot-separated file names', () => {
    expect(geminiCommandFileName('ks/dev')).toBe('ks.dev.toml');
    expect(geminiCommandFileName('review')).toBe('review.toml');
  });

  it('recovers the slug segment from a command file path', () => {
    expect(commandSlugFromPath('/catalog/commands/review.md')).toBe('review');
    expect(commandSlugFromPath('/catalog/commands/review')).toBe('review');
  });
});
