// Turns an effective resource set plus a selection into the managed links one harness home needs.
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { compose } from '../composer/Composer.js';
import { escapesRoots } from '../dump/Containment.js';
import { collectWorkflowClosure } from '../dump/WorkflowDump.js';
import { composedIdentityBody, serializeClaudeAgentDocument } from '../projection/Materialize.js';
import { compareSlugs, findResource, listAgentResources, listResources } from '../resolver/Resource.js';
import type { EffectiveResourceSet, ResolvedResource } from '../resolver/Resource.js';
import type { AgentDefaults, HarnessDefaultSettings, Settings, SettingsValue } from '../settings/Settings.js';
import type { LinkHarness } from './HarnessHome.js';

export interface LinkSelection {
  readonly agents: readonly string[];
  readonly workflows: readonly string[];
  readonly all: boolean;
}

export interface LinkScope {
  /** Root agents to compose, sorted; every delegate they name joins the closure later. */
  readonly agents: readonly string[];
  readonly errors: readonly string[];
}

const unknownAgent = (slug: string): string =>
  `Unknown agent '${slug}'. Run 'outfitter list agents' to see resolvable agents.`;

const workflowAgents = (
  set: EffectiveResourceSet,
  settings: Settings,
  workflows: readonly string[],
  errors: string[],
): readonly string[] =>
  workflows.flatMap((slug) => {
    if (!settings.workflows!.includes(slug)) {
      errors.push(`Workflow '${slug}' is not enabled. Add it to 'workflows' in settings.yml to link it.`);
      return [];
    }
    const closure = collectWorkflowClosure(set, slug);
    errors.push(...closure.errors);
    return closure.agents;
  });

const explicitAgents = (set: EffectiveResourceSet, slugs: readonly string[], errors: string[]): readonly string[] =>
  slugs.filter((slug) => {
    if (findResource(set, 'agent', slug) !== undefined) return true;
    errors.push(unknownAgent(slug));
    return false;
  });

const nothingToLink =
  'Nothing to link: enable a workflow or set default_agent in settings.yml, or pass --agent, --workflow, or --all.';

/**
 * With no explicit selection the scope is everything the settings stack already opted into: every
 * enabled workflow root plus the default agent. `--all` widens it to every resolvable agent.
 */
export const resolveLinkScope = (
  set: EffectiveResourceSet,
  settings: Settings,
  selection: LinkSelection,
): LinkScope => {
  const errors: string[] = [];
  const explicit = selection.agents.length > 0 || selection.workflows.length > 0 || selection.all;
  const defaults = settings.defaultAgent === undefined ? [] : [settings.defaultAgent];
  const agents = new Set([
    ...(selection.all ? listResources(set, 'agent').map((agent) => agent.slug) : []),
    ...workflowAgents(set, settings, explicit ? selection.workflows : settings.workflows!, errors),
    ...explicitAgents(set, explicit ? selection.agents : defaults, errors),
  ]);

  if (errors.length === 0 && agents.size === 0) errors.push(nothingToLink);
  return { agents: [...agents].sort(compareSlugs), errors };
};

export interface LinkedAgent {
  readonly slug: string;
  /** Native Claude agent definition composed from the agent's full identity and loadout. */
  readonly document: string;
}

export interface LinkedMcpServer {
  readonly id: string;
  readonly server: Readonly<Record<string, unknown>>;
}

export interface LinkClosure {
  readonly agents: readonly LinkedAgent[];
  readonly skills: readonly ResolvedResource[];
  readonly commands: readonly ResolvedResource[];
  readonly mcpServers: readonly LinkedMcpServer[];
  /** Winning tree-root `agents.md`, the always-on shared context, when any layer provides one. */
  readonly sharedContextPath?: string;
  readonly warnings: readonly string[];
  readonly errors: readonly string[];
}

const generatedMarker = (slug: string): string =>
  `<!-- Generated by \`outfitter link\` from agents/${slug}. Edit the .agents tree and relink; edits here are replaced. -->`;

const addSkills = (
  skills: Map<string, ResolvedResource>,
  selected: readonly ResolvedResource[],
  warnings: string[],
) => {
  for (const skill of selected) {
    if (escapesRoots(dirname(skill.winner.path), [skill.winner.layer.root])) {
      warnings.push(`skill '${skill.slug}' resolves outside its layer and is not linked.`);
    } else {
      skills.set(skill.slug, skill);
    }
  }
};

const addMcpServers = (
  servers: Map<string, LinkedMcpServer>,
  ids: readonly string[],
  definitions: Readonly<Record<string, unknown>>,
  agent: string,
  warnings: string[],
): void => {
  for (const id of ids) {
    const server = definitions[id];
    /* v8 ignore next -- composition only selects ids it resolved to a definition. */
    if (server === null || typeof server !== 'object') continue;
    const existing = servers.get(id);
    if (existing === undefined) servers.set(id, { id, server: server as Record<string, unknown> });
    else if (JSON.stringify(existing.server) !== JSON.stringify(server))
      warnings.push(`MCP server '${id}' is defined differently by agent '${agent}'; the first definition is linked.`);
  }
};

const commandsInScope = (set: EffectiveResourceSet, agents: readonly string[]): readonly ResolvedResource[] => {
  const commands = new Map(listResources(set, 'command').map((command) => [command.slug, command]));
  for (const agent of agents) {
    for (const command of listAgentResources(set, agent, 'command')) commands.set(command.slug, command);
  }
  return [...commands.values()]
    .filter((command) => !escapesRoots(command.winner.path, [command.winner.layer.root]))
    .sort((left, right) => compareSlugs(left.slug, right.slug));
};

/** Composes every scoped agent and its delegates, collecting what a harness home must carry. */
export const composeLinkClosure = (
  set: EffectiveResourceSet,
  scope: readonly string[],
  projectDirectory: string,
  agentDefaults?: AgentDefaults,
): LinkClosure => {
  const seen = new Set<string>();
  const queue = [...scope];
  const agents: LinkedAgent[] = [];
  const skills = new Map<string, ResolvedResource>();
  const mcpServers = new Map<string, LinkedMcpServer>();
  const warnings: string[] = [];
  const errors: string[] = [];

  while (queue.length > 0) {
    const slug = queue.shift()!;
    if (seen.has(slug)) continue;
    seen.add(slug);
    const composed = compose(set, slug, { projectDirectory, agentDefaults });
    warnings.push(...composed.warnings);
    if (composed.plan === undefined) {
      errors.push(...composed.errors);
      continue;
    }
    const { plan } = composed;
    warnings.push(...plan.warnings);
    agents.push({
      slug,
      document: serializeClaudeAgentDocument({
        slug,
        description: plan.identity.description ?? plan.identity.label,
        model: plan.loadout.model,
        thinking: plan.loadout.thinking,
        tools: plan.loadout.tools,
        skills: plan.loadout.skills.map((skill) => skill.slug),
        extensions: plan.loadout.extensions,
        body: `${generatedMarker(slug)}\n\n${composedIdentityBody(plan.identity)}`,
      }),
    });
    addSkills(skills, plan.loadout.skills, warnings);
    addMcpServers(mcpServers, plan.loadout.mcp, plan.loadout.mcpServers, slug, warnings);
    queue.push(...plan.loadout.subagents.map((subagent) => subagent.slug).sort(compareSlugs));
  }

  const sharedContextPath = set.layers.map((layer) => join(layer.root, 'agents.md')).find((path) => existsSync(path));
  return {
    agents: agents.sort((left, right) => compareSlugs(left.slug, right.slug)),
    skills: [...skills.values()].sort((left, right) => compareSlugs(left.slug, right.slug)),
    commands: commandsInScope(set, [...seen]),
    mcpServers: [...mcpServers.values()].sort((left, right) => compareSlugs(left.id, right.id)),
    sharedContextPath,
    warnings: [...new Set(warnings)],
    errors,
  };
};

export type LinkEntryKind = 'symlink' | 'file' | 'mcp' | 'setting';

export interface LinkedSetting {
  readonly file: 'settings.json' | 'config.toml';
  readonly keys: readonly string[];
  readonly value: SettingsValue;
}

/** One managed item inside a harness home, addressed relative to that home. */
export interface LinkEntry {
  readonly kind: LinkEntryKind;
  /** Path relative to the harness home, POSIX-joined. */
  readonly path: string;
  /** Absolute symlink target. */
  readonly target?: string;
  /** Generated file content. */
  readonly content?: string;
  readonly mcp?: LinkedMcpServer;
  readonly setting?: LinkedSetting;
  /** `kind:slug` of the protocol resource this entry projects, for diagnostics. */
  readonly resource: string;
}

export interface HarnessLinkPlan {
  readonly harness: LinkHarness;
  readonly entries: readonly LinkEntry[];
  readonly warnings: readonly string[];
}

const symlinkEntry = (path: string, target: string, resource: string): LinkEntry => ({
  kind: 'symlink',
  path,
  target,
  resource,
});

const sharedContextEntry = (closure: LinkClosure, fileName: string): readonly LinkEntry[] =>
  closure.sharedContextPath === undefined ? [] : [symlinkEntry(fileName, closure.sharedContextPath, 'root:agents.md')];

const skillEntries = (closure: LinkClosure): readonly LinkEntry[] =>
  closure.skills.map((skill) =>
    symlinkEntry(`skills/${skill.slug}`, dirname(skill.winner.path), `skill:${skill.slug}`),
  );

const commandEntries = (closure: LinkClosure, container: string): readonly LinkEntry[] =>
  closure.commands.map((command) =>
    symlinkEntry(`${container}/${command.slug}`, command.winner.path, `command:${command.slug}`),
  );

const mcpEntries = (closure: LinkClosure): readonly LinkEntry[] =>
  closure.mcpServers.map((mcp) => ({ kind: 'mcp', path: `mcp:${mcp.id}`, mcp, resource: `mcp:${mcp.id}` }));

const agentEntries = (closure: LinkClosure): readonly LinkEntry[] =>
  closure.agents.map((agent) => ({
    kind: 'file',
    path: `agents/${agent.slug}.md`,
    content: agent.document,
    resource: `agent:${agent.slug}`,
  }));

const settingEntries = (harness: LinkHarness, defaults: HarnessDefaultSettings | undefined): readonly LinkEntry[] => {
  const entries: LinkEntry[] = [];
  const file = harness === 'codex' ? 'config.toml' : 'settings.json';
  const visit = (value: SettingsValue, keys: readonly string[]): void => {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      for (const [key, child] of Object.entries(value)) visit(child, [...keys, key]);
      return;
    }
    entries.push({
      kind: 'setting',
      path: `setting:${file}:${keys.map(encodeURIComponent).join('/')}`,
      setting: { file, keys, value },
      resource: `harness_defaults.${harness}.${keys.join('.')}`,
    });
  };
  for (const [key, value] of Object.entries(defaults ?? {})) visit(value, [key]);
  return entries;
};

/**
 * Maps the closure onto one harness's native layout. Claude Code reads `skills/`, `agents/`,
 * `commands/`, and `CLAUDE.md` from its config directory; Codex reads `skills/`, `prompts/`, and
 * `AGENTS.md` from `CODEX_HOME`. Both take user-scope MCP servers only through their own CLIs.
 */
export const planHarnessLinks = (
  closure: LinkClosure,
  harness: LinkHarness,
  defaults?: HarnessDefaultSettings,
): HarnessLinkPlan => {
  if (harness === 'pi') {
    return {
      harness,
      entries: [...skillEntries(closure), ...settingEntries(harness, defaults)],
      warnings:
        closure.agents.length === 0
          ? []
          : ['pi has one native agent identity; composed agent identities are not linked.'],
    };
  }
  if (harness === 'claude') {
    return {
      harness,
      entries: [
        ...sharedContextEntry(closure, 'CLAUDE.md'),
        ...skillEntries(closure),
        ...agentEntries(closure),
        ...commandEntries(closure, 'commands'),
        ...mcpEntries(closure),
        ...settingEntries(harness, defaults),
      ],
      warnings: [],
    };
  }

  const identities = closure.agents.map((agent) => agent.slug);
  return {
    harness,
    entries: [
      ...sharedContextEntry(closure, 'AGENTS.md'),
      ...skillEntries(closure),
      ...commandEntries(closure, 'prompts'),
      ...mcpEntries(closure),
      ...settingEntries(harness, defaults),
    ],
    warnings:
      identities.length === 0
        ? []
        : [`codex has no native agent definitions; identities for ${identities.join(', ')} are not linked.`],
  };
};
