// Translates a catalog Markdown command into Gemini CLI's TOML custom-command format.
//
// Claude Code and Codex both read a custom command as a Markdown file, so those harnesses take a
// symlink and stay live-editable. Gemini instead reads `~/.gemini/commands/<name>.toml` with
// `description` and `prompt` keys, so its commands must be generated. This is the one place where
// a catalog resource cannot be projected by a symlink.
import { basename, extname } from 'node:path';

import { parseYamlDocument } from '../validation/YamlDocument.js';

export interface CommandDocument {
  readonly description?: string;
  readonly prompt: string;
}

const frontmatterDelimiter = '---';

/**
 * Splits optional YAML frontmatter from the command body. A command file without frontmatter is
 * entirely prompt text, which is the common case for Claude-style commands.
 */
export const parseCommandDocument = (content: string, commandPath: string): CommandDocument => {
  const lines = content.split('\n');

  if (lines[0]?.trimEnd() !== frontmatterDelimiter) {
    return { prompt: content.trim() };
  }

  const closingIndex = lines.findIndex((line, index) => index > 0 && line.trimEnd() === frontmatterDelimiter);

  if (closingIndex === -1) {
    return { prompt: content.trim() };
  }

  const parsed = parseYamlDocument(lines.slice(1, closingIndex).join('\n'), commandPath);
  const prompt = lines
    .slice(closingIndex + 1)
    .join('\n')
    .trim();

  if (!parsed.ok || parsed.document === null || typeof parsed.document !== 'object' || Array.isArray(parsed.document)) {
    return { prompt };
  }

  const { description } = parsed.document as { readonly description?: unknown };

  return { prompt, ...(typeof description === 'string' ? { description } : {}) };
};

/** TOML basic-string escapes that have a documented shorthand form. */
const TOML_SHORTHAND_ESCAPES: Readonly<Record<string, string>> = {
  '\\': '\\\\',
  '"': '\\"',
  '\n': '\\n',
  '\r': '\\r',
  '\t': '\\t',
};

const DELETE_CODE_POINT = 0x7f;
const FIRST_PRINTABLE_CODE_POINT = 0x20;

/**
 * Renders a TOML basic string. Gemini command prompts are multi-line Markdown, and TOML basic
 * strings are the only form that can carry arbitrary text with escapes, so newlines are encoded
 * rather than emitted literally. Written by hand because Outfitter has no TOML dependency and this
 * is the only TOML the CLI produces.
 *
 * A single pass over code points rather than chained replaces: TOML forbids every raw control
 * character, and enumerating them as a regex character class is both unreadable and flagged as a
 * control-character regex.
 */
export const toTomlString = (value: string): string => {
  let escaped = '';

  for (const character of value) {
    const shorthand = TOML_SHORTHAND_ESCAPES[character];

    if (shorthand !== undefined) {
      escaped += shorthand;
      continue;
    }

    const codePoint = character.codePointAt(0)!;
    const isControl = codePoint < FIRST_PRINTABLE_CODE_POINT || codePoint === DELETE_CODE_POINT;

    escaped += isControl ? `\\u${codePoint.toString(16).padStart(4, '0')}` : character;
  }

  return `"${escaped}"`;
};

/** Renders a parsed command as a Gemini custom-command TOML document. */
export const renderGeminiCommand = (document: CommandDocument): string => {
  const lines = [
    '# Generated by `outfitter link`. Edits are overwritten; change the source command instead.',
    ...(document.description === undefined ? [] : [`description = ${toTomlString(document.description)}`]),
    `prompt = ${toTomlString(document.prompt)}`,
  ];

  return `${lines.join('\n')}\n`;
};

/**
 * Command slugs are path-like (`ks/dev`), but Gemini namespaces commands with `.` in the filename
 * (`ks.dev.toml`), matching how a namespaced command is invoked.
 */
export const geminiCommandFileName = (slug: string): string => `${slug.split('/').join('.')}.toml`;

/** Strips a command file's extension to recover the slug segment used for the generated name. */
export const commandSlugFromPath = (commandPath: string): string => basename(commandPath, extname(commandPath));
