// Projects a compiled profile registry into each harness home as native artifacts: the Pi profile
// registry the runtime extension switches with, Claude Code native agent definitions selectable
// with `claude --agent <slug>`, and Codex native config profiles selectable with
// `codex --profile <slug>`. Every generated artifact embeds the composition fingerprint, and the
// applier reconciles idempotently under the same ownership rules as `outfitter link` (OFTR-012):
// an unmanaged file is a conflict and is never overwritten or deleted.

import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmdirSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';

import { stringify as stringifyToml } from 'smol-toml';

import { serializeClaudeAgentDocument } from '../projection/Materialize.js';
import type { LinkHarness } from '../links/HarnessHome.js';
import type { CompiledProfile, ProfileRegistry } from './ProfileCompiler.js';

/** Harness elements a compiled-profile projection can express natively. */
const supportedProfileElements: Record<LinkHarness, readonly string[]> = {
  pi: ['identity', 'skills', 'model', 'thinking', 'tools'],
  claude: ['identity', 'skills', 'model', 'thinking', 'tools'],
  codex: ['identity', 'model', 'thinking'],
};

/** The loadout elements one compiled profile actually selects (identity is always present). */
const profileElementsInUse = (profile: CompiledProfile): readonly string[] => {
  const present = ['identity'];
  if (profile.skills.length > 0) present.push('skills');
  if (profile.subagents.length > 0) present.push('subagents');
  if (Object.keys(profile.mcpServers).length > 0) present.push('mcp');
  if (profile.model !== undefined) present.push('model');
  if (profile.thinking !== undefined) present.push('thinking');
  if (profile.toolAllowlist !== undefined || profile.toolDenylist.length > 0) present.push('tools');
  return present;
};

/**
 * Which selected elements the harness's native profile surface cannot carry. `extensions` is
 * deliberately absent (OFTR-006.6.7): it names pi extension packages, and no user setting can make
 * another harness load them, so reporting it would describe Outfitter internals, not user choices.
 */
export const unsupportedProfileElements = (harness: LinkHarness, profile: CompiledProfile): readonly string[] =>
  profileElementsInUse(profile).filter((element) => !supportedProfileElements[harness].includes(element));

export interface ProfileArtifact {
  /** Path relative to the harness home, POSIX-joined. */
  readonly path: string;
  readonly content: string;
  /** `kind:slug` of what this artifact projects, for diagnostics and the ownership manifest. */
  readonly resource: string;
  readonly fingerprint: string;
}

export interface ProfileProjectionPlan {
  readonly harness: LinkHarness;
  readonly artifacts: readonly ProfileArtifact[];
  /** Per-profile unsupported elements, mirrored into the parity index for machine readers. */
  readonly unsupported: Readonly<Record<string, readonly string[]>>;
  readonly warnings: readonly string[];
}

const generatedMarker = (generator: string, fingerprint: string): string =>
  `<!-- Generated by ${generator}; fingerprint ${fingerprint}. Edit the .agents tree and re-run 'outfitter sync'; edits here are replaced. -->`;

/** The manifest that records ownership and fingerprints of projected profile artifacts. */
export interface ProfileManifest {
  readonly version: 1;
  readonly harness: LinkHarness;
  readonly entries: readonly { readonly path: string; readonly resource: string; readonly fingerprint: string }[];
}

const serializeJson = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

const piRegistryArtifact = (registry: ProfileRegistry): ProfileArtifact => ({
  path: 'outfitter/profiles/registry.json',
  content: serializeJson(registry),
  resource: 'profile-registry',
  fingerprint: 'sha256:registry',
});

const claudeAgentArtifact = (profile: CompiledProfile): ProfileArtifact => ({
  path: `agents/${profile.agent}.md`,
  content: `${generatedMarker('outfitter sync', profile.fingerprint)}\n\n${serializeClaudeAgentDocument({
    slug: profile.agent,
    description: profile.description ?? profile.label,
    model: profile.model,
    thinking: profile.thinking,
    tools:
      profile.toolAllowlist === undefined ? undefined : { allow: profile.toolAllowlist, deny: profile.toolDenylist },
    skills: profile.skills.map((skill) => skill.slug),
    extensions: [],
    body: profile.systemPrompt,
  })}`,
  resource: `agent:${profile.agent}`,
  fingerprint: profile.fingerprint,
});

const codexInstructionArtifact = (profile: CompiledProfile): ProfileArtifact => ({
  path: `outfitter/agents/${profile.agent}.md`,
  content: `${generatedMarker('outfitter sync', profile.fingerprint)}\n\n${profile.systemPrompt}\n`,
  resource: `instructions:${profile.agent}`,
  fingerprint: profile.fingerprint,
});

/** One Codex native config profile: the `[profiles.<slug>]` table Codex's `--profile` selects. */
const codexProfileTable = (profile: CompiledProfile, home: string): string => {
  const table: Record<string, unknown> = {};
  if (profile.model !== undefined) table.model = profile.model;
  if (profile.thinking !== undefined) table.model_reasoning_effort = profile.thinking;
  table.instructions = join(home, 'outfitter', 'agents', `${profile.agent}.md`);
  const header = [
    `# Generated by outfitter sync from agents/${profile.agent}; edits here are replaced.`,
    `# fingerprint: ${profile.fingerprint}`,
    '',
  ].join('\n');
  return `${header}${stringifyToml({
    profiles: { [profile.agent]: table },
  })}`;
};

const codexConfigArtifact = (profile: CompiledProfile, home: string): ProfileArtifact => ({
  path: `${profile.agent}.config.toml`,
  content: codexProfileTable(profile, home),
  resource: `profile:${profile.agent}`,
  fingerprint: profile.fingerprint,
});

/**
 * Plans one harness's native artifacts for the compiled registry. The Codex artifacts carry a
 * `fingerprint:` comment because TOML has no metadata channel, and the Claude artifact carries it
 * in its generated marker; both are machine-inspectable for parity checks.
 */
export const planProfileProjection = (
  registry: ProfileRegistry,
  harness: LinkHarness,
  home: string,
): ProfileProjectionPlan => {
  const warnings: string[] = [];
  const unsupported: Record<string, readonly string[]> = {};
  const artifacts: ProfileArtifact[] = [];

  if (harness === 'pi') {
    if (registry.profiles.length > 0) artifacts.push(piRegistryArtifact(registry));
    for (const profile of registry.profiles) {
      const missing = unsupportedProfileElements(harness, profile);
      if (missing.length > 0) unsupported[profile.agent] = missing;
    }
    return { harness, artifacts, unsupported, warnings };
  }

  for (const profile of registry.profiles) {
    unsupported[profile.agent] = unsupportedProfileElements(harness, profile);
    if (harness === 'claude') {
      artifacts.push(claudeAgentArtifact(profile));
      continue;
    }
    artifacts.push(codexInstructionArtifact(profile));
    artifacts.push(codexConfigArtifact(profile, home));
  }
  artifacts.push({
    path: 'outfitter/profiles.json',
    content: serializeJson({
      version: 1,
      harness,
      profiles: registry.profiles.map((profile) => ({
        agent: profile.agent,
        fingerprint: profile.fingerprint,
        // Every claude/codex profile gains an unsupported entry in the loop above.
        /* v8 ignore next */
        unsupported: unsupported[profile.agent] ?? [],
      })),
    }),
    resource: 'profile-index',
    fingerprint: 'sha256:index',
  });
  return { harness, artifacts, unsupported, warnings };
};

export type ProfileActionStatus = 'created' | 'updated' | 'unchanged' | 'conflict' | 'removed';

export interface ProfileAction {
  readonly harness: LinkHarness;
  readonly path: string;
  readonly status: ProfileActionStatus;
  readonly detail?: string;
}

interface ManifestEntry {
  readonly path: string;
  readonly resource: string;
  readonly fingerprint: string;
}

const manifestPath = (home: string): string => join(home, '.outfitter', 'profiles.json');

const readManagedManifest = (home: string, harness: LinkHarness): readonly ManifestEntry[] => {
  const path = manifestPath(home);
  if (!existsSync(path)) return [];
  let parsed: Partial<ProfileManifest>;
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8')) as Partial<ProfileManifest>;
  } catch {
    return [];
  }
  if (parsed.harness !== harness || !Array.isArray(parsed.entries)) return [];
  const isEntry = (entry: unknown): entry is ManifestEntry => {
    /* v8 ignore next -- null/non-object manifest entries are defensive against hand edits. */
    if (entry === null || typeof entry !== 'object') return false;
    const candidate = entry as Partial<ManifestEntry>;
    return (
      typeof candidate.path === 'string' &&
      typeof candidate.resource === 'string' &&
      typeof candidate.fingerprint === 'string'
    );
  };
  return parsed.entries.filter(isEntry);
};

const isRegularFile = (path: string): boolean => {
  try {
    return lstatSync(path).isFile();
  } catch {
    return false;
  }
};

const writeManifest = (home: string, manifest: ProfileManifest): void => {
  const path = manifestPath(home);
  if (manifest.entries.length === 0) {
    rmSync(path, { force: true });
    try {
      rmdirSync(dirname(path));
    } catch {
      // Absent or still holds other files; not ours to remove.
    }
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, serializeJson(manifest));
};

/** Paths the persistent `outfitter link` manifest records are Outfitter-managed too. */
const linkManagedPaths = (home: string): ReadonlySet<string> => {
  const path = join(home, '.outfitter', 'links.json');
  if (!existsSync(path)) return new Set();
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as {
      readonly entries?: readonly { readonly path?: unknown }[];
    };
    /* v8 ignore next -- malformed link entries are defensive against hand edits. */
    return new Set(
      (parsed.entries ?? [])
        .map((entry) => (typeof entry?.path === 'string' ? entry.path : undefined))
        .filter((value): value is string => value !== undefined),
    );
  } catch {
    return new Set();
  }
};

const removeEmptyParents = (home: string, relativePath: string): void => {
  let parent = dirname(join(home, relativePath));
  const homeRoot = join(home);
  while (parent.startsWith(homeRoot) && parent !== homeRoot) {
    let empty: boolean;
    try {
      empty = readdirSync(parent).length === 0;
    } catch {
      /* v8 ignore next -- the directory vanished concurrently; nothing is ours to remove. */
      return;
    }
    if (!empty) return;
    try {
      rmdirSync(parent);
    } catch {
      /* v8 ignore next -- the directory vanished or filled concurrently; leave it be. */
      return;
    }
    parent = dirname(parent);
  }
};

interface ArtifactReconciliation {
  readonly action: ProfileAction;
  /** True when the artifact is owned by the projection manifest after this reconciliation. */
  readonly owned: boolean;
}

const lstatSyncSafe = (path: string): boolean => {
  try {
    return lstatSync(path) !== undefined;
  } catch {
    return false;
  }
};

/** Reconciles one artifact against the home under the OFTR-012 ownership rules. */
const reconcileArtifact = (
  plan: ProfileProjectionPlan,
  artifact: ProfileArtifact,
  home: string,
  isManaged: (path: string) => boolean,
): ArtifactReconciliation => {
  const path = join(home, artifact.path);
  const write = (): void => {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, artifact.content);
  };
  if (!existsSync(path) && !lstatSyncSafe(path)) {
    write();
    return { action: { harness: plan.harness, path: artifact.path, status: 'created' }, owned: true };
  }
  if (!isRegularFile(path)) {
    return {
      action: {
        harness: plan.harness,
        path: artifact.path,
        status: 'conflict',
        detail: 'an unmanaged directory or symlink already exists here',
      },
      owned: false,
    };
  }
  if (readFileSync(path, 'utf8') === artifact.content) {
    return { action: { harness: plan.harness, path: artifact.path, status: 'unchanged' }, owned: true };
  }
  if (!isManaged(artifact.path)) {
    return {
      action: {
        harness: plan.harness,
        path: artifact.path,
        status: 'conflict',
        detail: 'an unmanaged file already exists here',
      },
      owned: false,
    };
  }
  write();
  return { action: { harness: plan.harness, path: artifact.path, status: 'updated' }, owned: true };
};

/**
 * Reconciles one harness's plan into its home: writes only owned or new files, reports conflicts
 * for unmanaged paths, keeps byte-identical files untouched, and removes managed artifacts that
 * left the registry. Identical replays perform no filesystem mutation at all.
 */
export const applyProfileProjection = (plan: ProfileProjectionPlan, home: string): readonly ProfileAction[] => {
  const managed = new Map(readManagedManifest(home, plan.harness).map((entry) => [entry.path, entry]));
  const linkOwned = linkManagedPaths(home);
  const planned = new Set(plan.artifacts.map((artifact) => artifact.path));
  const isManaged = (path: string): boolean => managed.has(path) || linkOwned.has(path);

  const reconciliations = plan.artifacts.map((artifact) => reconcileArtifact(plan, artifact, home, isManaged));
  const actions: ProfileAction[] = reconciliations.map((reconciliation) => reconciliation.action);
  const owned = new Set(reconciliations.filter((r) => r.owned).map((r) => r.action.path));

  const retained: ManifestEntry[] = plan.artifacts
    .filter((artifact) => owned.has(artifact.path))
    .map((artifact) => ({ path: artifact.path, resource: artifact.resource, fingerprint: artifact.fingerprint }));
  for (const [path, entry] of managed) {
    if (planned.has(path)) continue;
    const absolute = join(home, path);
    /* v8 ignore next 4 -- a manifest entry whose file vanished externally stays owned, never deleted. */
    if (!isRegularFile(absolute)) {
      retained.push(entry);
      continue;
    }
    unlinkSync(absolute);
    removeEmptyParents(home, path);
    actions.push({ harness: plan.harness, path, status: 'removed', detail: entry.resource });
  }

  writeManifest(home, { version: 1, harness: plan.harness, entries: retained });
  return actions;
};
